import { AmplifyAuthenticator } from "@aws-amplify/ui-react";
import { Amplify, API, Auth, withSSRContext } from "aws-amplify";
import type { NextPage, GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { listCourses } from "../src/graphql/queries";
import styles from "../styles/Home.module.css";
import awsExports from "../src/aws-exports";

Amplify.configure({ ...awsExports, ssr: true });

export const getServerSideProps: GetServerSideProps = async ({ req }) => {
  const SSR = withSSRContext({ req });
  const response = await SSR.API.graphql({ query: listCourses });

  return {
    props: {
      courses: response.data.listCourses.items,
    },
  };
};

type HomeProps = {
  courses: Array<{
    id: string;
    name: string;
  }>;
};

const Home: NextPage<HomeProps> = ({ courses = [] }) => {
  const showCourses = courses.length > 0;

  return (
    <div className={styles.container}>
      <Head>
        <title>Amplify + Next.js (POC)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Amplify + Next.js (POC)</h1>

        {!showCourses && (
          <p className={styles.description}>
            There are not courses at this moment
          </p>
        )}

        {showCourses && (
          <>
            <p className={styles.description}>Courses</p>

            <div className={styles.grid}>
              {courses.map((course) => (
                <a href={`/course/${course.id}`} key={course.id}>
                  <div className={styles.card}>
                    <Image
                      className={styles.cardImage}
                      src={`https://via.placeholder.com/250/000000/FFFFFF/?text=${course.name}`}
                      alt={course.name}
                      width={250}
                      height={250}
                    />
                    <div>
                      <h2>{course.name}</h2>
                    </div>
                  </div>
                </a>
              ))}
            </div>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/darthzyklus"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by @darthzyklus
        </a>
      </footer>
    </div>
  );
};

export default Home;
